project:
  name: quickstart-tableau-server
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  s3_bucket: ''
tests:
  linux:
    parameters:
      AcceptEULA: 'yes'
      InstanceType: m6i.4xlarge
      OS: Linux
      KeyPairName: $[alfred_getkeypair]
      Route53: a
      DomainName: tableau
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: quickstart-tableau-server/
      QSS3BucketRegion: us-west-2
      RegCity: Test City
      RegCompany: Test Company
      RegCountry: Test Country
      RegDepartment: Test Department
      RegEmail: testemail@example.com
      RegFirstName: Test First Name
      RegIndustry: Test Industry
      RegLastName: Test Last Name
      RegPhone: Test Phone
      RegState: Test State
      RegTitle: Test Title
      RegZip: Test Zip
      TableauServerAdminPassword: $[alfred_genpass_32]
      TableauServerAdminUser: admin
      TableauServerLicenseKey: ''
      TsmUsername: tsmadmin
      TsmPassword: $[alfred_genpass_32]
    regions:
    - us-west-2
    s3_bucket: ''
    template: templates/parent-stack.template
