project:
  name: quickstart-tableau-server
  owner: quickstart-eng@amazon.com
  s3_bucket: quickstart-testing-public
  regions:
  - us-west-2
tests:
  linux:
    parameters: 
      OS: Linux
      Route53HostedZone: Z03034441712JY0KSJGD1
      Route53DomainName: awsquickstart.tableau.com
      S3BucketName: tableau-server-data-bucket2
      AcceptEULA: 'yes'
      InstanceType: m6i.4xlarge
      KeyPairName: takashi-quickstart
      LatestAmiId: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
      TableauServerAdminPassword: $[alfred_genpass_32]
      TableauServerAdminUser: admin
      LicenseKey: ''
      TsmUsername: tsmadmin
      TsmPassword: $[alfred_genpass_32]
      QSS3BucketName: quickstart-testing-public
      QSS3KeyPrefix: quickstart-tableau-server/
      QSS3BucketRegion: us-west-2
      RegCity: Test City
      RegCompany: Test Company
      RegCountry: Test Country
      RegDepartment: Test Department
      RegEmail: testemail@example.com
      RegFirstName: Test First Name
      RegIndustry: Test Industry
      RegLastName: Test Last Name
      RegPhone: Test Phone
      RegState: Test State
      RegTitle: Test Title
      RegZip: Test Zip
    template: templates/parent-stack.template
  windows:
    parameters: 
      OS: Windows
      Route53HostedZone: Z03034441712JY0KSJGD1
      Route53DomainName: awsquickstart.tableau.com
      S3BucketName: tableau-server-data-bucket2
      AcceptEULA: 'yes'
      InstanceType: m6i.4xlarge
      KeyPairName: takashi-quickstart
      LatestAmiId: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
      TableauServerAdminPassword: $[alfred_genpass_32]
      TableauServerAdminUser: admin
      LicenseKey: ''
      TsmUsername: tsmadmin
      TsmPassword: $[alfred_genpass_32]
      QSS3BucketName: quickstart-testing-public
      QSS3KeyPrefix: quickstart-tableau-server/
      QSS3BucketRegion: us-west-2
      RegCity: Test City
      RegCompany: Test Company
      RegCountry: Test Country
      RegDepartment: Test Department
      RegEmail: testemail@example.com
      RegFirstName: Test First Name
      RegIndustry: Test Industry
      RegLastName: Test Last Name
      RegPhone: Test Phone
      RegState: Test State
      RegTitle: Test Title
      RegZip: Test Zip
    template: templates/parent-stack.template
