project:
  name: quickstart-tableau-server
  owner: quickstart-eng@amazon.com
  s3_bucket: ''
  package_lambda: false
  s3_regional_buckets: true
  shorten_stack_name: true
  regions:
  - us-west-2
  tags:
    Name: Tableau Server Quickstart
    Creator: tbinns@tableau.com
    Group: tbinns@tableau.com  
    DeptCode: "429"
    Environment: Dev
    Application: AWS Quickstarts
    Description: Resources used by Tableau Server Quickstart testing
  parameters:
    AvailabilityZones: $[taskcat_genaz_2]
    Route53HostedZone: Z03034441712JY0KSJGD1
    Route53DomainName: awsquickstart.tableau.com
    TableauS3BucketName: ''
    AcceptEULA: 'yes'
    InstanceType: m6i.4xlarge
    KeyPairName: $[taskcat_getkeypair]
    SourceCIDR: 10.0.0.0/16
    TableauServerAdminPassword: $[taskcat_genpass_32]
    TableauServerAdminUser: admin
    LicenseKey: ''
    TsmUsername: tsmadmin
    TsmPassword: $[taskcat_genpass_32]
    QSS3BucketName: $[taskcat_autobucket]
    QSS3KeyPrefix: quickstart-tableau-server/
    QSS3BucketRegion: $[taskcat_current_region]
    RegCity: Test City
    RegCompany: Test Company
    RegCountry: Test Country
    RegDepartment: Test Department
    RegEmail: testemail@example.com
    RegFirstName: Test First Name
    RegIndustry: Test Industry
    RegLastName: Test Last Name
    RegPhone: Test Phone
    RegState: Test State
    RegTitle: Test Title
    RegZip: Test Zip
    RegOptIn: "false"
    RegCompanyEmployees: "5"
tests:
  tableau-linux:
    parameters: 
      OS: Linux
      TableauServerSubDomainName: tab-linux-$[taskcat_random-string]
    template: templates/tableau-single-server-main.template.yaml
    regions:
      - us-west-1
      - us-west-2
      - us-east-1
      - us-east-2
  tableau-windows:
    parameters:
      OS: Windows
      TableauServerSubDomainName: tab-linux-$[taskcat_random-string]
    template: templates/tableau-single-server-main.template.yaml
    regions:
      - us-west-1
      - us-west-2
      - us-east-1
      - us-east-2
