project:
  name: quickstart-tableau-server
  owner: quickstart-eng@amazon.com
  s3_bucket: ''
  package_lambda: false
  s3_regional_buckets: true
  shorten_stack_name: true
  regions:
  - us-west-2
  tags:
    Name: Tableau Server Quickstart
    Creator: tbinns@tableau.com
    Group: tbinns@tableau.com  
    DeptCode: "429"
    Environment: Dev
    Application: AWS Quickstarts
    Description: Resources used by Tableau Server Quickstart testing
tests:
  linux:
    parameters: 
      OS: Windows
      Route53HostedZone: Z03034441712JY0KSJGD1
      Route53DomainName: awsquickstart.tableau.com
      S3BucketName: tableau-data-$[taskcat_random-string]
      AcceptEULA: 'yes'
      InstanceType: m6i.4xlarge
      KeyPairName: $[taskcat_getkeypair]
      SourceCIDR: 10.0.0.0/0
      LatestAmiId: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
      TableauServerAdminPassword: $[taskcat_genpass_32]
      TableauServerAdminUser: admin
      LicenseKey: ''
      TsmUsername: tsmadmin
      TsmPassword: $[taskcat_genpass_32]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: quickstart-tableau-server/
      QSS3BucketRegion: $[taskcat_current_region]
      RegCity: Test City
      RegCompany: Test Company
      RegCountry: Test Country
      RegDepartment: Test Department
      RegEmail: testemail@example.com
      RegFirstName: Test First Name
      RegIndustry: Test Industry
      RegLastName: Test Last Name
      RegPhone: Test Phone
      RegState: Test State
      RegTitle: Test Title
      RegZip: Test Zip
      RegOptIn: "false"
      RegCompanyEmployees: "5"
    template: templates/parent-stack.template
  # windows:
  #   parameters:
  #     OS: Windows
  #     Route53HostedZone: Z03034441712JY0KSJGD1
  #     Route53DomainName: awsquickstart.tableau.com
  #     S3BucketName: tableau-data-$[taskcat_random-string]
  #     AcceptEULA: 'yes'
  #     InstanceType: m6i.4xlarge
  #     KeyPairName: $[taskcat_getkeypair]
  #     SourceCIDR: 10.0.0.0/0
  #     LatestAmiId: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  #     TableauServerAdminPassword: $[alfred_genpass_32]
  #     TableauServerAdminUser: admin
  #     LicenseKey: ''
  #     TsmUsername: tsmadmin
  #     TsmPassword: $[alfred_genpass_32]
  #     QSS3BucketName: quickstart-testing-public
  #     QSS3KeyPrefix: quickstart-tableau-server/
  #     QSS3BucketRegion: $[taskcat_current_region]
  #     RegCity: Test City
  #     RegCompany: Test Company
  #     RegCountry: Test Country
  #     RegDepartment: Test Department
  #     RegEmail: testemail@example.com
  #     RegFirstName: Test First Name
  #     RegIndustry: Test Industry
  #     RegLastName: Test Last Name
  #     RegPhone: Test Phone
  #     RegState: Test State
  #     RegTitle: Test Title
  #     RegZip: Test Zip
  #     RegOptIn: "false"
  #     RegCompanyEmployees: "5"
  #   template: templates/parent-stack.template